// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIkBMoIla_vzKvK3bq_7yvVW-vfDVqbtk',
    appId: '1:888232445135:web:411872d80675fb463563ba',
    messagingSenderId: '888232445135',
    projectId: 'my-order-example-flutter-app',
    authDomain: 'my-order-example-flutter-app.firebaseapp.com',
    storageBucket: 'my-order-example-flutter-app.firebasestorage.app',
    measurementId: 'G-LH4N2Y0RRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7XJFzpS7cE_1qDj62TDANc5voVwraWlo',
    appId: '1:888232445135:android:7dc1fed11226ecc73563ba',
    messagingSenderId: '888232445135',
    projectId: 'my-order-example-flutter-app',
    storageBucket: 'my-order-example-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKwr2qEH6SisXfJpFmpmOAQ0oU4THkn0A',
    appId: '1:888232445135:ios:7440a7260769c9e03563ba',
    messagingSenderId: '888232445135',
    projectId: 'my-order-example-flutter-app',
    storageBucket: 'my-order-example-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.orderUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKwr2qEH6SisXfJpFmpmOAQ0oU4THkn0A',
    appId: '1:888232445135:ios:7440a7260769c9e03563ba',
    messagingSenderId: '888232445135',
    projectId: 'my-order-example-flutter-app',
    storageBucket: 'my-order-example-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.orderUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIkBMoIla_vzKvK3bq_7yvVW-vfDVqbtk',
    appId: '1:888232445135:web:202d977bd42606303563ba',
    messagingSenderId: '888232445135',
    projectId: 'my-order-example-flutter-app',
    authDomain: 'my-order-example-flutter-app.firebaseapp.com',
    storageBucket: 'my-order-example-flutter-app.firebasestorage.app',
    measurementId: 'G-SWK3RF5F18',
  );
}
